// Theme
export const THEME_SET = "THEME_SET";
export const THEMES = {
  DEFAULT: "DEFAULT",
  DARK: "DARK",
  LIGHT: "LIGHT",
  BLUE: "BLUE",
  GREEN: "GREEN",
  INDIGO: "INDIGO",
};

// Auth
export const AUTH_SIGN_IN_REQUEST = "AUTH_SIGN_IN_REQUEST";
export const AUTH_SIGN_IN_SUCCESS = "AUTH_SIGN_IN_SUCCESS";
export const AUTH_SIGN_IN_FAILURE = "AUTH_SIGN_IN_FAILURE";
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";
export const AUTH_SIGN_UP_REQUEST = "AUTH_SIGN_UP_REQUEST";
export const AUTH_SIGN_UP_SUCCESS = "AUTH_SIGN_UP_SUCCESS";
export const AUTH_SIGN_UP_FAILURE = "AUTH_SIGN_UP_FAILURE";
export const AUTH_SIGN_UP_EXPERT_REQUEST = "AUTH_SIGN_UP_REQUEST";
export const AUTH_SIGN_UP_EXPERT_SUCCESS = "AUTH_SIGN_UP_SUCCESS";
export const AUTH_SIGN_UP_EXPERT_FAILURE = "AUTH_SIGN_UP_FAILURE";
export const AUTH_RESET_PASSWORD_REQUEST = "AUTH_RESET_PASSWORD_REQUEST";
export const AUTH_RESET_PASSWORD_SUCCESS = "AUTH_RESET_PASSWORD_SUCCESS";
export const AUTH_RESET_PASSWORD_FAILURE = "AUTH_RESET_PASSWORD_FAILURE";

// User
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAILURE = "USER_LIST_FAILURE";

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAILURE = "USER_DETAIL_FAILURE";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";

// Patient
export const PATIENT_LIST_REQUEST = "PATIENT_LIST_REQUEST";
export const PATIENT_LIST_SUCCESS = "PATIENT_LIST_SUCCESS";
export const PATIENT_LIST_FAILURE = "PATIENT_LIST_FAILURE";

export const PATIENT_DETAIL_REQUEST = "PATIENT_DETAIL_REQUEST";
export const PATIENT_DETAIL_SUCCESS = "PATIENT_DETAIL_SUCCESS";
export const PATIENT_DETAIL_FAILURE = "PATIENT_DETAIL_FAILURE";

export const PATIENT_SEARCH_REQUEST = "PATIENT_SEARCH_REQUEST";
export const PATIENT_SEARCH_SUCCESS = "PATIENT_SEARCH_SUCCESS";
export const PATIENT_SEARCH_FAILURE = "PATIENT_SEARCH_FAILURE";

// Disease
export const DISEASE_LIST_REQUEST = "DISEASE_LIST_REQUEST";
export const DISEASE_LIST_SUCCESS = "DISEASE_LIST_SUCCESS";
export const DISEASE_LIST_FAILURE = "DISEASE_LIST_FAILURE";

// Request
export const REQUEST_LIST_REQUEST = "REQUEST_LIST_REQUEST";
export const REQUEST_LIST_SUCCESS = "REQUEST_LIST_SUCCESS";
export const REQUEST_LIST_FAILURE = "REQUEST_LIST_FAILURE";

export const REQUEST_DETAIL_REQUEST = "REQUEST_DETAIL_REQUEST";
export const REQUEST_DETAIL_SUCCESS = "REQUEST_DETAIL_SUCCESS";
export const REQUEST_DETAIL_FAILURE = "REQUEST_DETAIL_FAILURE";


